apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmanager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: taskmanager.peaceakintayo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taskmanager-service
            port:
              number: 80