{{- if .Values.prometheusIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "taskmanager.fullname" . }}-prometheus
  namespace: {{ .Values.prometheusIngress.namespace | default .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.prometheusIngress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.prometheusIngress.className }}
  rules:
    - host: {{ .Values.prometheusIngress.host }}
      http:
        paths:
          - path: {{ .Values.prometheusIngress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.prometheusIngress.serviceName }}
                port:
                  number: {{ .Values.prometheusIngress.servicePort }}
{{- end }}
