apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" . }}
  labels:
    app: {{ include "taskmanager.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ include "taskmanager.name" . }}
    version: {{ .Values.blueGreen.activeSlot }}